# Generated by Django 6.1.1 on 2026-09-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Компания / Организация')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('period', models.CharField(max_length=100, verbose_name='Период работы (например, 2024 — 2026)')),
                ('skills_and_achievements', models.TextField(verbose_name='Мои навыки и достижения')),
                ('description', models.TextField(verbose_name='Описание работы и обязанности')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='work_bg/', verbose_name='Фоновое изображение страницы')),
                ('page_number', models.PositiveIntegerField(default=1, verbose_name='Номер страницы в книге (1, 2, 3...)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Этап работы (Страница)',
                'verbose_name_plural': 'Этапы работы (Книга)',
                'ordering': ['page_number'],
            },
        ),
    ]
