# Generated by Django 6.1.1 on 2026-09-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_workexperience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['page_number'], 'verbose_name': 'Этап работы (Книга)', 'verbose_name_plural': 'Этапы работы (Книга)'},
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_bg/', verbose_name='Фоновый рисунок'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Организация / Компания'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=models.TextField(verbose_name='Описание работы'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='page_number',
            field=models.IntegerField(default=1, verbose_name='Номер страницы'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='period',
            field=models.CharField(max_length=100, verbose_name='Период (например: 2020 — 2022)'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Должность / Название этапа'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='skills_and_achievements',
            field=models.TextField(verbose_name='Навыки и достижения'),
        ),
    ]
