# Generated by Django 6.1.1 on 2026-09-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_workexperience_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, verbose_name='Должность / Заголовок')),
                ('company_name', models.CharField(max_length=200, verbose_name='Организация')),
                ('period', models.CharField(max_length=100, verbose_name='Период работы')),
                ('skills_and_achievements', models.TextField(blank=True, verbose_name='Навыки и достижения')),
                ('description', models.TextField(blank=True, verbose_name='Подробное описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages_photos/', verbose_name='Фото страницы')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Страница книги',
                'verbose_name_plural': 'Страницы книги',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Фото профиля')),
            ],
        ),
    ]
